blank_issues_enabled: false
contact_links:
  - name: "Report a Security Vulnerability or Risk"
    url: "https://github.com/canvas-ac"
    about: "If you find a dangerous Security Vulnerability, please email us in stead."
  - name: "Get a Quote"
    url: "https://canvas.ac/hiring"
    about: "Hire us for your project"
  - name: "Job Opportunities"
    url: "https://canvas.ac/careers"
    about: "Work with or at canvas"